apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-backend
      version: green
  template:
    metadata:
      labels:
        app: ecommerce-backend
        version: green
    spec:
      containers:
      - name: ecommerce-backend
        image: ecommerce-backend:green
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgres://admin:password123@postgres:5432/ecommerce
