apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-frontend
      version: green
  template:
    metadata:
      labels:
        app: ecommerce-frontend
        version: green
    spec:
      containers:
      - name: ecommerce-frontend
        image: ecommerce-frontend:green
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
