# Generated by Django 5.1.2 on 2025-06-26 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(help_text='Nombre de la categoría del producto', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(help_text='Nombre del producto', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto (máximo 10 dígitos, 2 decimales)', max_digits=10)),
                ('stock', models.IntegerField(help_text='Cantidad disponible en inventario')),
                ('ventas', models.IntegerField(default=0, help_text='Cantidad de veces que se ha vendido el producto')),
                ('imagen', models.BinaryField(blank=True, help_text='Imagen del producto en formati binario (opcional)', null=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
                ('vendedor', models.ForeignKey(help_text='Usuario vendedor del producto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
