# Generated by Django 5.1.2 on 2025-06-27 15:45

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(help_text='Nombre de la categoría del producto', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.BinaryField(blank=True, help_text='Imagen del producto en formato binario (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio del producto (máximo 10 dígitos, 2 decimales)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='El precio no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo.')]),
        ),
    ]
